[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    'VRGDAs/=lib/VRGDAs/src',
    'solmate/=lib/solmate/src',
    'erc6551/=lib/erc6551/src',
]
